### ISSUE TITLE
Python Flask @app.before_request avoid next function process

### ISSUE THREAD

**Issue by GalDayan** [supertokens/supertokens-python#346]
Hey there, I'm using Python with Flask.

My use case is to audit every HTTP request that comes into my server, via the `@app.before_requests` annotation that Flask provides.
The thing is when adding both `@app.before_request` and `@verify_session(session_required=False)`, the actual route that needs to handle the logic is not fired.

Example code:
```
@app.before_request
@verify_session(session_required=False)
def audit_request(response):
    user_id = None
    session: SessionContainer = g.supertokens

    if session:
        user_id = session.get_user_id()

    audit_entry = AuditLog(
        user_id=user_id,
        method=request.method,
        url=request.url,
        headers=dict(request.headers),
        data=request.get_json(silent=True)
    )
    db.session.add(audit_entry)
    db.session.commit()

    return response
```

Worth to say that if changing the `@app.before_request` to `@app.after_request` everything works

**Comment by rishabhpoddar** [comment]
This has been fixed in version >= 0.14.4

**Comment by GalDayan** [comment]
@rishabhpoddar Sorry to bother you guys, but I've installed 0.14.6 but it still not working

Source code:
```
@app.before_request # type: ignore
@verify_session(session_required=False)
def audit_request(response):
    user_id = None
    session: SessionContainer = g.supertokens
    return response
```

Error log:
```
raceback (most recent call last):
  File "/Users/talbarel/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/talbarel/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/talbarel/Library/Python/3.9/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/talbarel/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/talbarel/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/talbarel/Library/Python/3.9/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/talbarel/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/talbarel/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/Users/talbarel/Library/Python/3.9/lib/python/site-packages/supertokens_python/recipe/session/framework/flask/__init__.py", line 65, in wrapped_function
    response = f(*args, **kwargs)
TypeError: audit_request() missing 1 required positional argument: 'response'
```

**Comment by rishabhpoddar** [comment]
Thanks for more info. We will investigate further.

**Comment by KShivendu** [comment]
Hi @GalDayan,

Actually now the error is: `audit_request() missing 1 required positional argument: 'response'`

When using `@app.before_request`, the response doesn't exist. So try this instead:

```python
@app.before_request # type: ignore
@verify_session(session_required=False)
def audit_request(response):
    user_id = None
    session: SessionContainer = g.supertokens
    return response
```

We also added a test regarding your issue. You can see https://github.com/supertokens/supertokens-python/pull/348/files#diff-55cad2c4d170b4aab0bffdea437a22d45538509c7e7fe986fb05e7acbb673778R698 if that helps.

I hope this should suffice. Feel free to reopen this issue if you're still facing any problem :)
